openapi: "3.0.3"
info:
  version: 0.0.1
  title: Formel 1 API
  description: A small sample API to grasp the basics of the OpenAPI Specification
servers:
  - url: http://localhost:8080/api/v1/f1
paths:
  /drivers:
    get:
      tags:
        - Drivers
      summary: List all drivers
      responses:
        200:
          description: Found Drivers
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/DriverDto"
    post:
      tags:
        - Drivers
      summary: Add a new driver
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DriverDto"
      responses:
        201:
          description: Created a new driver
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DriverDto'
  /drivers/{uuid}:
    get:
      tags:
        - Driver
      summary: Returns a driver by uuid
      parameters:
        - in: path
          name: uuid
          schema:
            type: string
          required: true
          description: String of to uuid to get
      responses:
        200:
          description: Found driver
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DriverDto'
        404:
          description: No driver found with this uuid
    put:
      tags:
        - Driver
      summary: Update a driver
      parameters:
        - in: path
          name: uuid
          schema:
            type: string
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DriverDto"
      responses:
        200:
          description: The updated driver
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DriverDto'
        404:
          description: No driver found with this uuid
    delete:
      tags:
        - Driver
      summary: Delete a driver by uuid
      parameters:
        - in: path
          name: uuid
          schema:
            type: string
          required: true
          description: String of to uuid to delete
      responses:
        200:
          description: One driver deleted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DriverDto'
        404:
          description: No driver found with this uuid
  /racingteam:
    get:
      tags:
        - Racing Teams
      summary: List all racing teams
      responses:
        200:
          description: An paged array of racing teams
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/RacingTeamDto"
    post:
      tags:
        - Racing Teams
      summary: Add a new racing team
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RacingTeamDto"
      responses:
        201:
          description: Added a new racing team
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RacingTeamDto'
  /racingteam/{uuid}:
    get:
      tags:
        - Racing Team
      summary: Returns a racing team by uuid
      parameters:
        - in: path
          name: uuid
          schema:
            type: string
          required: true
          description: String of to uuid to get
      responses:
        200:
          description: Found one racing team
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RacingTeamDto'
        404:
          description: No racing team found with this uuid
    put:
      tags:
        - Racing Team
      summary: Update a racing team
      parameters:
        - in: path
          name: uuid
          schema:
            type: string
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RacingTeamDto"
      responses:
        200:
          description: The updated racing team
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RacingTeamDto'
        404:
          description: No racing team found with this uuid
    delete:
      tags:
        - Racing Team
      summary: Delete a racing team by uuid
      parameters:
        - in: path
          name: uuid
          schema:
            type: string
          required: true
          description: String of to uuid to delete
      responses:
        200:
          description: One racing team deleted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RacingTeamDto'
        404:
          description: No racing team found with this uuid
  /tracks:
    get:
      tags:
        - Tracks
      summary: List all tracks
      responses:
        200:
          description: Found tracks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/TrackDto"
    post:
      tags:
        - Tracks
      summary: Add a new track
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TrackDto"
      responses:
        201:
          description: Created a new track
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TrackDto'
  /tracks/{uuid}:
    get:
      tags:
        - Track
      summary: Returns a track by uuid
      parameters:
        - in: path
          name: uuid
          schema:
            type: string
          required: true
          description: String of to uuid to get
      responses:
        200:
          description: Found track
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TrackDto'
        404:
          description: No track found with this uuid
    put:
      tags:
        - Track
      summary: Update a track
      parameters:
        - in: path
          name: uuid
          schema:
            type: string
          required: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TrackDto"
      responses:
        200:
          description: The updated track
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TrackDto'
        404:
          description: No track found with this uuid
    delete:
      tags:
        - Track
      summary: Delete a track by uuid
      parameters:
        - in: path
          name: uuid
          schema:
            type: string
          required: true
          description: String of to uuid to delete
      responses:
        200:
          description: One track deleted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TrackDto'
        404:
          description: No track found with this uuid
components:
  schemas:
    DriverDto:
      required:
        - name
        - prename
        - age
        - country
        - points
      properties:
        uuid:
          type: string
          example: 123e4567-e89b-42d3-a456-556642440000
        name:
          type: string
          example: Müller
          minLength: 1
          maxLength: 255
        prename:
          type: string
          example: Hans
          minLength: 1
          maxLength: 255
        age:
          type: integer
          example: 20
          minimum: 18
          maximum: 100
        racingTeam:
          $ref: "#/components/schemas/RacingTeamDto"
        points:
          type: integer
          example: 15
          minimum: 0
          maximum: 600
        country:
          type: string
          example: Switzerland
          minLength: 1
          maxLength: 255
    RacingTeamDto:
      required:
        - name
        - teamBoss
        - engineProducer
        - country
        - points
      properties:
        uuid:
          type: string
          example: 123e4567-e89b-42d3-a456-556642440000
        name:
          type: string
          example: TestTeam
          minLength: 1
          maxLength: 255
        teamBoss:
          type: string
          example: Klaus
          minLength: 1
          maxLength: 255
        engineProducer:
          type: string
          example: Ferrari
          minLength: 1
          maxLength: 255
        country:
          type: string
          example: Switzerland
          minLength: 1
          maxLength: 255
        points:
          type: integer
          example: 0
          minimum: 0
          maximum: 1200
    TrackDto:
      required:
        - name
        - location
        - lenght
        - country
        - rounds
      properties:
        uuid:
          type: string
          example: 123e4567-e89b-42d3-a456-556642440000
        name:
          type: string
          example: Red Bull Ring
          minLength: 1
          maxLength: 255
        location:
          type: string
          example: Steiermark
          minLength: 1
          maxLength: 255
        lenght:
          type: double
          example: 5.44
          minLength: 1
          maxLength: 255
        country:
          type: string
          example: Switzerland
          minLength: 1
          maxLength: 255
        rounds:
          type: integer
          example: 50
          minimum: 0
          maximum: 120
