openapi: "3.0.3"
info:
  version: 0.0.1
  title: Formel 1 API
  description: A small sample API to grasp the basics of the OpenAPI Specification
servers:
  - url: http://localhost:8080/api/v1/f1
paths:
  /drivers:
    get:
      summary: List all drivers
      responses:
        200:
          description: An paged array of drivers
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/DriverDto"
    post:
      summary: Add a new driver
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/DriverDto"
      responses:
        200:
          description: An paged array of drivers
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/DriverDto"
  /racingteam:
    get:
      summary: List all Racing Teams
      responses:
        200:
          description: An paged array of Racing Teams
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/RacingTeamDto"
    post:
      summary: Add a new Racing Team
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RacingTeamDto"
      responses:
        200:
          description: An paged array of drivers
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/RacingTeamDto"
components:
  schemas:
    DriverDto:
      required:
        - name
        - prename
        - age
        - country
        - points
      properties:
        uuid:
          type: string
          example: 123e4567-e89b-42d3-a456-556642440000
        name:
          type: string
          example: Müller
          minLength: 1
          maxLength: 255
        prename:
          type: string
          example: Hans
          minLength: 1
          maxLength: 255
        age:
          type: integer
          example: 20
          minimum: 18
          maximum: 100
        racingTeam:
          type: object
          $ref: "#/components/schemas/RacingTeamDto"
        points:
          type: integer
          example: 15
          minimum: 0
          maximum: 600
        country:
          type: string
          example: Switzerland
          minLength: 1
          maxLength: 255
    RacingTeamDto:
      required:
        - name
        - teamBoss
        - engineProducer
        - country
        - points
      properties:
        uuid:
          type: string
          example: 123e4567-e89b-42d3-a456-556642440000
        name:
          type: string
          example: TestTeam
          minLength: 1
          maxLength: 255
        teamBoss:
          type: string
          example: Klaus
          minLength: 1
          maxLength: 255
        engineProducer:
          type: string
          example: Ferrari
          minLength: 1
          maxLength: 255
        country:
          type: string
          example: Switzerland
          minLength: 1
          maxLength: 255
        points:
          type: integer
          example: 0
          minimum: 0
          maximum: 1200
